#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
#=================================================

name: OpenWRT-x86-64bit

on:
#  release:
#    types: published
  push:
    branches:
      - master
    paths:
      - '.github/workflows/openwrt-x64.yml'
      - 'step/01-prepare_package.sh'
      - 'seed/x86.seed'
  schedule:
    - cron: 35 20 * * *
  watch:
    types: started

jobs:
    build:
      runs-on: ubuntu-18.04
      if: github.event.repository.owner.id == github.event.sender.id

      steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Show CPU Model and Free Space
        run: |
          echo -e "Total CPU cores\t: $(nproc)"
          cat /proc/cpuinfo | grep 'model name'
          free -h

      - name: Set env
        run: |
          echo "SSH_ACTIONS=false" >> $GITHUB_ENV
          echo "UPLOAD_BIN_DIR=false" >> $GITHUB_ENV
          echo "UPLOAD_FIRMWARE=true" >> $GITHUB_ENV
          echo "UPLOAD_RELEASE=true" >> $GITHUB_ENV
          echo "CONFIG_FILE=x86.seed" >> $GITHUB_ENV
          echo "TZ=Asia/Shanghai" >>$GITHUB_ENV
          echo "Build_Date=$(date +%Y.%m.%d)" >> $GITHUB_ENV
          
      - name: Show env
        run: echo $GITHUB_ENV

      - name: free disk space
        run: |
          df -h
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
          /bin/bash ./script/free_disk_space.sh
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E rm -rf /etc/apt/sources.list.d
          sudo -E apt-get update -y
          sudo -E apt-get install -y build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python3 python3-pip python3-ply haveged lrzsz device-tree-compiler scons
          wget -qO - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | sed 's/python-/python3-/g' | /bin/bash
          sudo -E apt-get clean -y
          git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
          df -h
          
      - name: Install OpenWrt source
        run: |
          git clone -b master --single-branch https://git.openwrt.org/openwrt/openwrt.git openwrt

      - name: Prepare openwrt
        run: |
          cd openwrt
          cp -r ../step/* ./
          /bin/bash 00-prepare_openwrt.sh

      - name: Prepare application packages
        run: |
          cd openwrt
          /bin/bash 01-prepare_package.sh

#      - name: Remove Upx
#        run: |
#          cd openwrt
#          /bin/bash 02-remove_upx.sh

      - name: Add ACL
        run: |
          cd openwrt
          /bin/bash 03-create_acl_for_luci.sh -a

      - name: Load Config
        run: |
          cd openwrt
          mv ../seed/$CONFIG_FILE .config
          make defconfig
          chmod -R 755 ./

      - name: Make Toolchain
        run: |
          cd openwrt
          let make_process=$(nproc)+1
          make toolchain/install -j${make_process} V=s

      - name: Compile Openwrt
        run: |
          cd openwrt
          let make_process=$(nproc)+1
          make -j${make_process} V=s || make -j${make_process} V=s

      - name: Organize files
        id: organize
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv openwrt/bin/targets/x86/64/*combined.img* ./artifact/
          cd ./artifact/
          gzip -d *.gz && exit 0
          gzip *.img
          zip x64-sfs-$(date +%Y-%m-%d).zip *squashfs*
          cd ../openwrt
          cp .config ../artifact/x64.config
          ./scripts/diffconfig.sh > ../artifact/x64.seed

      - name: Upload artifact
        uses: actions/upload-artifact@main
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        with:
          name: OpenWrt_X86-64bit_firmware
          path: ./artifact/

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.7.3
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          name: OpenWrt x86-64bit
          allowUpdates: true
          tag: OpenWrt
          commit: master
          replacesArtifacts: true
          token: ${{ secrets.RELEASES_TOKEN }}
          bodyFile: "body-origin.md"
          artifacts: ./artifact/*.zip,./artifact/x64.*
